config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get ":page", to: "static_pages#page", as: :static_page

  root 'static_pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def page
    @page_title = page_params[:page]
    if published_page?(@page_title)
      render "#{@page_title}.html.erb"
    else
      redirect_to :root
    end
  end

  private

    def page_params
      params.permit(:page)
    end

    def published_pages
      %w[home projects contributions about]
    end

    def published_page?(page)
      published_pages.include?(page)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="icon-container">
      <a href="https://github.com/rlmoser99" target="_blank">
        <div class="icon-circle inverted"><i class="fab fa-github"></i></div>
      </a>
      <a href= "mailto: moser.rachel@gmail.com">
        <div class="icon-circle"><i class="far fa-envelope"></i></div>
      </a>
      <a href= "https://www.linkedin.com/in/rlmoser99/" target="_blank">
        <div class="icon-circle"><i class="fab fa-linkedin-in"></i></div>
      </a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-container">
    <div class="menu-wrap">
      <input type="checkbox" class="toggler">
      <div class="hamburger">
        <div></div>
      </div>
      <div class="header-title">
        <% unless current_page?(root_url) %>
          <h3 class="page-title">
              <%= @page_title %>
          </h3>
        <% end %>
      </div>
      <div class="menu">
        <div>
          <div>
            <ul>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Projects', static_page_path('projects')%></li>
              <li><%= link_to 'Contributions', static_page_path('contributions')%></li>
              <li><%= link_to 'About', static_page_path('about')%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rachel Moser's Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Euphoria+Script&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/934a39e35a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'rlm-favicon.png' %>
  </head>

  <body>
  
    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/static_pages/about.html.erb
<main>
  <%= render "layouts/header" %>
  <div class="content about">
    <div class="about-container">
      <div class="about-content">
        <div class="card">
          <p class="card-summary">
            I'm a Ruby on Rails Developer who is committed to learning new tools to add to my toolbox. I am known as a creative problem solver with <code>&lt;strong&gt;</code> attention to detail and organizational skills. I value looking at the big picture and thinking outside of the <code>{flex}</code> box.
          </p>
          <p class="card-summary">
            I enjoy creating art in various mediums, riding rollercoasters, reading historical fiction, solving logic puzzles (like
            <a href="https://www.brainbashers.com/hitorihelp.asp" target="_blank">Hitori</a> and Sudoku), and playing board games (like
            <a href="https://boardgamegeek.com/boardgame/36218/dominion" target="_blank">Dominion</a>,
            <a href="https://boardgamegeek.com/boardgame/38821/settlers-catan-gallery-edition" target="_blank">Settlers of Catan</a>, and
            <a href="https://boardgamegeek.com/boardgame/9209/ticket-ride" target="_blank">Ticket to Ride</a>).
          </p>
        </div>

        <h3>Background</h3>
        <p>
          I decided to learn web development after having a few small tastes of programming, like creating excel macros to simplify bookkeeping reports or creating custom forms in medical record software. I began learning on my own, but found myself in "tutorial hell,” doing various introductory material but not making much overall progress.
        </p>
        <p>
          Once I joined <a href="https://www.theodinproject.com/" target="_blank">The Odin Project</a> (TOP) in November 2019, I finally started making the real progress I had been looking for! TOP's project-based curriculum forced me to break down each project into pseudo code, get comfortable researching, and reading documentation. In addition, I wanted to get better at reading and debugging other people's code, so I started helping students in the TOP Discord community.
        </p>
        <p>
          I have experienced many highs and lows working through the curriculum. One of my lowest moments was in the Ruby testing section because I struggled to wrap my head around it. So I explored several other resources, hoping to gain more understanding. But everything I found covered the same introductory material or pertained to Rails.
        </p>
        <p>
          I knew testing was important in the Ruby community, so I decided to dig deeper into each individual testing concept. Reading through the testing questions asked in the TOP Discord gave me the idea to create something that would benefit other students. Over the course of several months, I created a <a href="https://github.com/rlmoser99/ruby_rspec_TOP" target="_blank">16-lesson tutorial</a> designed to better equip TOP students to test their Ruby projects. Before I submitted this tutorial to TOP's curriculum, I invited fellow students to review and contribute to it.
        </p>
        <p>
          In June 2020, I was invited to be part of <a href="https://github.com/TheOdinProject" target="_blank">TOP's maintainer team</a>. This team of volunteers, from all over the world, maintains TOP’s open source curriculum and Discord community. After working with this team for 6 months, I was invited to be part of their core team. This core team handles the logistical decisions and is comprised of about half of the members of the maintainer team. Joining this team of experienced developers has given me the opportunity to collaborate with others and work in a shared code base.
        </p>
      </div>
      <div class="about-images">
        <%= image_tag("art-woodbox.png", title: "wood burning design on wooden case", class: "rotate-left") %>
        <%= image_tag("art-string.png", title: "geometrical art made with string", class: "rotate-right") %>
        <%= image_tag("art-sticker.png", title: "Settlers of Catan inspired laptop sticker", class: "rotate-left") %>
      </div>
    </div>
  </div>
</main>

app/views/static_pages/contact.html.erb
<h1>Contact Page</h1>

app/views/static_pages/contributions.html.erb
<main>
  <%= render "layouts/header" %>
  <div class="content project">

    <div class="project-container">
      <div id="rspec-tutorial" class="project-img playground-img">
      </div>
      <div class="card">
        <div class="card-header">
          <h3>Ruby RSpec Tutorial</h3>
          <div class="btn-group">
            <a href="https://www.theodinproject.com/courses/ruby-programming/lessons/testing-your-ruby-code#assignment-1" class="left-btn" target="_blank">Lesson</a>
            <a href="https://github.com/rlmoser99/ruby_rspec_TOP" class="right-btn" target="_blank">
              <i class="fas fa-code"></i>
            </a>
          </div>
        </div>
        <div class="card-description">
          <p class="card-summary">
            Wrote a unit testing tutorial to contribute to The Odin Project's curriculum.
          </p>

          <ul>
            <li>Developed 16 lessons that cover the following: built-in matchers, the 'Arrange, Act & Assert' testing pattern, stubs, mocks, doubles, and test-driven development.</li>
            <li>Prepared corresponding prompts for students to experience writing a wide variety of tests.</li>
            <li>Invited other students to review and contribute before it was published in the curriculum.</li>
            <li>Reduced student questions by 30% in the Ruby testing support channel on Discord as a result of integrating this tutorial into the curriculum.</li>
          <ul>
        </div>
      </div>
    </div>

    <div class="project-container project-reverse">
      <div class="project-img odin-img">
      </div>
      <div class="card">
        <div class="card-header">
          <h3>Other Significant Contributions</h3>
        </div>
        <div class="card-description">
          <p class="card-summary">
            Contributions to The Odin Project's curriculum and Ruby on Rails app.
          </p>

          <ul>
            <li>
              Wrote a lesson on
              <strong>
                <%= link_to "Nested Collections", "https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/nested-collections", target: "_blank" %>
              </strong>
              to help students understand their complexities.
              <%= link_to "https://github.com/TheOdinProject/curriculum/pull/22214", title: "Source Code", target: "_blank", class: "icon-link" do %>
                <i class="fas fa-code"></i>
              <% end %>
            </li>
            <li>
              Wrote an article,
              <strong>
                <%= link_to "How to Help Others Solve Coding Problems", "https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community#how-to-help-others-solve-coding-problems", target: "_blank" %>,
              </strong>
               to help our Discord community.
              <%= link_to "https://github.com/TheOdinProject/curriculum/pull/22280", title: "Source Code", target: "_blank", class: "icon-link" do %>
                <i class="fas fa-code"></i>
              <% end %>
            </li>
            <li>
              Created and refactored multiple
              <strong>
                test-driven development exercises
              </strong>
              to reinforce Ruby lessons.
              <%= link_to "https://github.com/TheOdinProject/ruby-exercises/pulls?q=is%3Apr+author%3Arlmoser99+is%3Aclosed", title: "Source Code", target: "_blank", class: "icon-link" do %>
                <i class="fas fa-code"></i>
              <% end %>
            </li>
            <li>
              Wrote
              <strong>
                system tests
              </strong>
               to increase our test coverage.
              <%= link_to "https://github.com/TheOdinProject/theodinproject/pulls?q=is%3Apr+author%3Arlmoser99+is%3Aclosed+System+Tests", title: "Source Code", target: "_blank", class: "icon-link" do %>
                <i class="fas fa-code"></i>
              <% end %>
            </li>
          <ul>
        </div>
      </div>
    </div>

  </div>
</main>

app/views/static_pages/home.html.erb
<main class="main-dark">
  <%= render "layouts/header" %>
  <div class="content hero">
    <div class="hero-image">
      <%= image_tag('rlm_logo.png') %>
    </div>

    <div class="hero-title">
      <h1>Rachel Moser</h1>
      <h2>Ruby on Rails Developer</h2>
      <div class="hero-links">
          <%= link_to 'Projects', static_page_path('projects') %>
          <%= link_to 'Contributions', static_page_path('contributions') %>
          <%= link_to 'About', static_page_path('about') %>
      </div>
    </div>

  </div>
</main>

app/views/static_pages/projects.html.erb
<main>
  <%= render "layouts/header" %>
  <div class="content project">

    <div class="project-container">
      <div class="project-img social-media-img">
      </div>
      <div class="card">
        <div class="card-header">
          <h3>Social Media</h3>
          <div class="btn-group">
            <a href="https://rlm-social-media.herokuapp.com/users/sign_in" class="left-btn" target="_blank">Demo</a>
            <a href="https://github.com/rlmoser99/social-media" class="right-btn" target="_blank">
              <i class="fas fa-code"></i>
            </a>
          </div>
        </div>
        <div class="card-description">
          <p class="card-summary">
            Ruby on Rails web app that replicates the core functionality of Facebook.
          </p>

          <ul>
            <li>Implemented <strong>Hotwire</strong> to handle real-time updates of posts, comments, and likes.</li>
            <li>Wrote tests using <strong>RSpec, Capybara, and Shoulda Matchers</strong>.</li>
            <li>Used <strong>ActiveStorage and Cloudinary</strong> to allow users to upload images.</li>
            <li>Utilized <strong>service objects</strong> to manage notifications and friendships.</li>
          </ul>

        </div>
      </div>
    </div>

    <div class="project-container project-reverse">
      <div class="project-img flight-booker-img">
      </div>
      <div class="card">
        <div class="card-header">
          <h3>Flight Booker</h3>
          <div class="btn-group">
            <a href="https://rlm-flight-booker.herokuapp.com/" class="left-btn" target="_blank">Demo</a>
            <a href="https://github.com/rlmoser99/flight-booker" class="right-btn" target="_blank">
              <i class="fas fa-code"></i>
            </a>
          </div>
        </div>
        <div class="card-description">
          <p class="card-summary">
            Ruby on Rails web app for booking a 1-way flight.
          </p>

          <ul>
            <li>Implemented a bonus feature that finds two connecting flights for long cross-country trips.</li>
            <li>Utilized test-driven development for the connecting flight feature, as part of its <strong>RSpec test suite</strong>.</li>
            <li>Managed continuous creation and deletion of database entries using <strong>rake tasks and Heroku Scheduler</strong>.</li>
          </ul>

        </div>
      </div>
    </div>

    <div class="project-container">
      <div class="project-img chess-img">
      </div>
      <div class="card">
        <div class="card-header">
          <h3>Chess</h3>
          <div class="btn-group">
            <a href="https://repl.it/@rlmoser/rubychess" class="left-btn" target="_blank">Demo</a>
            <a href="https://github.com/rlmoser99/ruby_chess" class="right-btn" target="_blank">
              <i class="fas fa-code"></i>
            </a>
          </div>
        </div>
        <div class="card-description">
          <p class="card-summary">
            Ruby command-line game for 1 or 2 players.
          </p>

          <ul>
            <li>Implemented <strong>strategy, factory, and observer design patterns</strong> to abstract code duplication and reduce explicit message passing.</li>
            <li>Focused on writing <strong>RSpec unit tests using test-driven development</strong>.</li>
            <li>Utilized serialization to validate each move and allow the user to save their game.</li>
          <ul>
        </div>
      </div>
    </div>

  </div>
</main>